### ISSUE TITLE
Update Github Action to test multiple Python and Postgres versions

### ISSUE THREAD

**Issue by steve52** [nycdb/nycdb#254]
We should update the new Github Action to run `pytest tests` with a variety of supported Python and Postrgres versions.

Travis was testing these:
 ```
   - env:
        PYTHON_VERSION: 3.12-rc-bullseye
        POSTGRES_VERSION: 15
    - env:
        PYTHON_VERSION: 3.11-bullseye
        POSTGRES_VERSION: 15
    - env:
        PYTHON_VERSION: 3.11-bullseye
        POSTGRES_VERSION: 14
    - env:
        PYTHON_VERSION: 3.10-bullseye
        POSTGRES_VERSION: 14
    - env:
        PYTHON_VERSION: 3.10-bullseye
        POSTGRES_VERSION: 13
    - env:
        PYTHON_VERSION: 3.10-bullseye
        POSTGRES_VERSION: 12
    - env:
        PYTHON_VERSION: 3.9-bullseye
        POSTGRES_VERSION: 14
    - env:
        PYTHON_VERSION: 3.8-bullseye
        POSTGRES_VERSION: 14
```
